config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :readstatuses
  resources :shapes
  resources :bookstores
  resources :efgs
  get "booklists/displayx(/:ind)" => "booklists#displayx"
  get "booklists/finish(/:ind)" => "booklists#finish"
  get "home/index" => "home#show"
  get "booklists/index2(/:ind)" => "booklists#index2"
  get "booklists/index3(/:ind)" => "booklists#index3"
  # root to: "home#index"

  # get "kindlelists/show(/:id)" => "kindlelists#show"

  resources :abcs
  resources :efgs
  resources :calibrelists
  resources :readinglists
  resources :kindlelists, only: [:show, :index, :new, :edit]

  resources :booklists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "booklists#index"
end

app/models/shape.rb
class Shape < ApplicationRecord
end

app/controllers/shapes_controller.rb
class ShapesController < ApplicationController
  before_action :set_shape, only: %i[ show edit update destroy ]

  # GET /shapes or /shapes.json
  def index
    @shapes = Shape.all
  end

  # GET /shapes/1 or /shapes/1.json
  def show
  end

  # GET /shapes/new
  def new
    @shape = Shape.new
  end

  # GET /shapes/1/edit
  def edit
  end

  # POST /shapes or /shapes.json
  def create
    @shape = Shape.new(shape_params)

    respond_to do |format|
      if @shape.save
        format.html { redirect_to shape_url(@shape), notice: "Shape was successfully created." }
        format.json { render :show, status: :created, location: @shape }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @shape.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shapes/1 or /shapes/1.json
  def update
    respond_to do |format|
      if @shape.update(shape_params)
        format.html { redirect_to shape_url(@shape), notice: "Shape was successfully updated." }
        format.json { render :show, status: :ok, location: @shape }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @shape.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shapes/1 or /shapes/1.json
  def destroy
    @shape.destroy!

    respond_to do |format|
      format.html { redirect_to shapes_url, notice: "Shape was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shape
      @shape = Shape.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shape_params
      params.require(:shape).permit(:name)
    end
end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/views/shapes/_form.html.erb
<%= form_with(model: shape) do |form| %>
  <% if shape.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(shape.errors.count, "error") %> prohibited this shape from being saved:</h2>

      <ul>
        <% shape.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/shapes/_shape.html.erb
<div id="<%= dom_id shape %>">
  <p>
    <strong>Name:</strong>
    <%= shape.name %>
  </p>

</div>

app/views/shapes/edit.html.erb
<% content_for :title, "Editing shape" %>

<h1>Editing shape</h1>

<%= render "form", shape: @shape %>

<br>

<div>
  <%= link_to "Show this shape", @shape %> |
  <%= link_to "Back to shapes", shapes_path %>
</div>

app/views/shapes/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Shapes" %>

<h1>Shapes</h1>

<div id="shapes">
  <% @shapes.each do |shape| %>
    <%= render shape %>
    <p>
      <%= link_to "Show this shape", shape %>
    </p>
  <% end %>
</div>

<%= link_to "New shape", new_shape_path %>

app/views/shapes/new.html.erb
<% content_for :title, "New shape" %>

<h1>New shape</h1>

<%= render "form", shape: @shape %>

<br>

<div>
  <%= link_to "Back to shapes", shapes_path %>
</div>

app/views/shapes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @shape %>

<div>
  <%= link_to "Edit this shape", edit_shape_path(@shape) %> |
  <%= link_to "Back to shapes", shapes_path %>

  <%= button_to "Destroy this shape", @shape, method: :delete %>
</div>