config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :readstatuses
  resources :shapes
  resources :bookstores
  resources :efgs
  get "booklists/displayx(/:ind)" => "booklists#displayx"
  get "booklists/finish(/:ind)" => "booklists#finish"
  get "home/index" => "home#show"
  get "booklists/index2(/:ind)" => "booklists#index2"
  get "booklists/index3(/:ind)" => "booklists#index3"
  # root to: "home#index"

  # get "kindlelists/show(/:id)" => "kindlelists#show"

  resources :abcs
  resources :efgs
  resources :calibrelists
  resources :readinglists
  resources :kindlelists, only: [:show, :index, :new, :edit]

  resources :booklists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "booklists#index"
end

app/models/bookstore.rb
class Bookstore < ApplicationRecord
end

app/controllers/bookstores_controller.rb
class BookstoresController < ApplicationController
  before_action :set_bookstore, only: %i[ show edit update destroy ]

  # GET /bookstores or /bookstores.json
  def index
    @bookstores = Bookstore.all
  end

  # GET /bookstores/1 or /bookstores/1.json
  def show
  end

  # GET /bookstores/new
  def new
    @bookstore = Bookstore.new
  end

  # GET /bookstores/1/edit
  def edit
  end

  # POST /bookstores or /bookstores.json
  def create
    @bookstore = Bookstore.new(bookstore_params)

    respond_to do |format|
      if @bookstore.save
        format.html { redirect_to bookstore_url(@bookstore), notice: "Bookstore was successfully created." }
        format.json { render :show, status: :created, location: @bookstore }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bookstore.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookstores/1 or /bookstores/1.json
  def update
    respond_to do |format|
      if @bookstore.update(bookstore_params)
        format.html { redirect_to bookstore_url(@bookstore), notice: "Bookstore was successfully updated." }
        format.json { render :show, status: :ok, location: @bookstore }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bookstore.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookstores/1 or /bookstores/1.json
  def destroy
    @bookstore.destroy!

    respond_to do |format|
      format.html { redirect_to bookstores_url, notice: "Bookstore was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bookstore
      @bookstore = Bookstore.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bookstore_params
      params.require(:bookstore).permit(:name)
    end
end

app/helpers/bookstores_helper.rb
module BookstoresHelper
end

app/views/bookstores/_bookstore.html.erb
<div id="<%= dom_id bookstore %>">
  <p>
    <strong>Name:</strong>
    <%= bookstore.name %>
  </p>

</div>

app/views/bookstores/_form.html.erb
<%= form_with(model: bookstore) do |form| %>
  <% if bookstore.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(bookstore.errors.count, "error") %> prohibited this bookstore from being saved:</h2>

      <ul>
        <% bookstore.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/bookstores/edit.html.erb
<% content_for :title, "Editing bookstore" %>

<h1>Editing bookstore</h1>

<%= render "form", bookstore: @bookstore %>

<br>

<div>
  <%= link_to "Show this bookstore", @bookstore %> |
  <%= link_to "Back to bookstores", bookstores_path %>
</div>

app/views/bookstores/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Bookstores" %>

<h1>Bookstores</h1>

<div id="bookstores">
  <% @bookstores.each do |bookstore| %>
    <%= render bookstore %>
    <p>
      <%= link_to "Show this bookstore", bookstore %>
    </p>
  <% end %>
</div>

<%= link_to "New bookstore", new_bookstore_path %>

app/views/bookstores/new.html.erb
<% content_for :title, "New bookstore" %>

<h1>New bookstore</h1>

<%= render "form", bookstore: @bookstore %>

<br>

<div>
  <%= link_to "Back to bookstores", bookstores_path %>
</div>

app/views/bookstores/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @bookstore %>

<div>
  <%= link_to "Edit this bookstore", edit_bookstore_path(@bookstore) %> |
  <%= link_to "Back to bookstores", bookstores_path %>

  <%= button_to "Destroy this bookstore", @bookstore, method: :delete %>
</div>