config/routes.rb
Rails.application.routes.draw do
  resources :categories
  resources :readstatuses
  resources :shapes
  resources :bookstores
  resources :efgs
  get "booklists/displayx(/:ind)" => "booklists#displayx"
  get "booklists/finish(/:ind)" => "booklists#finish"
  get "home/index" => "home#show"
  get "booklists/index2(/:ind)" => "booklists#index2"
  get "booklists/index3(/:ind)" => "booklists#index3"
  # root to: "home#index"

  # get "kindlelists/show(/:id)" => "kindlelists#show"

  resources :abcs
  resources :efgs
  resources :calibrelists
  resources :readinglists
  resources :kindlelists, only: [:show, :index, :new, :edit]

  resources :booklists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "booklists#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sidebar_link_to(path, emoji, text)
    classes = %w[my-1 nav-link text-white]
    classes << "active" if current_page?(path)

    link_to(path, class: classes) do
      tag.span(class: "me-2") { emoji } + tag.span { text }
    end
  end

  def icon(icon_name)
    tag.i(class: ["bi", "bi-#{icon_name}"])
  end

  def icon_with_text(icon_name, text)
    tag.span(icon(icon_name), class: "me-2") + tag.span(text)
  end

  def turbo_stream_flash
    turbo_stream.update "flash", partial: "flash"
  end
end

app/views/application/_flash.html.erb
<% if notice %>
  <div class="alert alert-primary alert-dismissible">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <%= notice %>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible">
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    <%= alert %>
  </div>
<% end %>

app/views/application/_sidebar.html.erb
<div class="d-flex flex-column flex-shrink-0 py-3 px-3 bg-dark text-white vh-100">
  <div class="d-flex align-items-center justify-content-center py-2">
    <%= link_to "AMS", root_path, class: "text-white display-6 text-decoration-none" %>
  </div>
  <hr />

  <ul class="nav nav-pills flex-column mb-auto">
    <li class="nav-item">
      <%= sidebar_link_to(booklists_path, "🐱", "booklist") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(calibrelists_path, "🐶", "calibrelist") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(kindlelists_path, "🐣", "kindlelist") %>
    </li>
    <li class="nav-item">
      <%= sidebar_link_to(readinglists_path, "🦔", "readinglist") %>
    </li>
  </ul>
</div>